services:
  - type: web
    name: pdfme-app
    env: node
    buildCommand: 'npm install && pip install -r requirements.txt'
    startCommand: 'node server.js'
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
