services:
  - type: web
    name: pdfme-app
    env: node
    buildCommand: |
      apt-get update
      apt-get install -y pandoc
      npm install
    startCommand: 'node server.js'
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
